### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Laande** [JOY6IX9INE/Discord-Lootbox-Opener#3]
typing-extensions is required with tls-client, and for some reason installing tls-client doesnt install typing-extensions
Should be added to requirements.txt

For people having the same problem as me, just run :
`pip install typing-extensions`

**Comment by JOY6IX9INE** [comment]
I've added it to the requirements.txt to ensure others don't encounter the same hiccup. Your willingness to share your expertise is truly appreciated.
